### ISSUE TITLE
Github Actions can't find this action.

### ISSUE THREAD

**Issue by jwg4** [ams0/acr-task-github-action#2]
Hi, I have run a build successfully using this action a few days ago.

Today I saw: 
Failed to resolve action download info. Error: Unable to resolve action `ams0/acr-task-github-action@v1`, unable to find version `v1`
on my build: https://github.com/jwg4/t-tetromino/runs/1714352945?check_suite_focus=true

I saw that you have a v2 available so I changed the workflow to use this version and got a similar message:
https://github.com/jwg4/t-tetromino/pull/8/checks?check_run_id=1714368385

You can see in the repo that my use of the action is very straightforward.

If you have any ideas as to the cause or a workaround I would be very grateful! Thanks in advance.

**Comment by ams0** [comment]
Really sorry, I cleaned up my github and I restored the repo from backups, but I didn't re-published it. It should work now with @v2

Let me know!

**Comment by mahalel** [comment]
Hi, any chance you could update the readme to include the v2 in the example given please? Currently still using v1.

**Comment by ams0** [comment]
Hi

thanks for your comment, currently the repo has been deprecated in favor of https://github.com/Azure/acr-build . I will update the Readme accordingly
